language: rust
sudo: required
os:
- linux
- osx
rust:
- stable
services:
- docker
before_script:
  - rustup component add rustfmt
  - rustup component add clippy
script:
  # Require `cargo fmt` to have been run.
  - cargo fmt -- --check
  # Require clippy to pass without warnings. 
  - cargo clippy
  # Build the code.
  - cargo build
before_deploy: "./build-release jira-terminal ${TRAVIS_TAG}-${TRAVIS_OS_NAME}"
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: "jira-terminal-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.*"
  skip_cleanup: true
  on:
    rust: stable
    tags: true
